name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - run: mkdir -p screens logs
      - run: sudo apt-get install xvfb

      - name: Run Nightwatch component tests
        run: xvfb-run --auto-servernum npm run test:components

      - name: Build and start application
        run: npm start &

      - name: Wait until it starts
        run: sleep 30s

      - name: Run Nightwatch end-to-end tests
        run: xvfb-run --auto-servernum npm run test:e2e

